# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package MacOs

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: macos-11
    
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "${{ matrix.python-version }}"
    - name: Run tests
      run: |
        pip install .
        pip install -r requirements-dev.txt
        py.test
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel twine
    - name: "Build package for python ${{ matrix.python-version }}"
      run: |
        python setup.py bdist_wheel
    - name: Publish distribution 📦 to Test PyPI
      env:
        TWINE_USERNAME: __token__
        #TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        #python -m twine upload --repository testpypi dist/* --verbose --skip-existing
        python -m twine upload dist/* --verbose --skip-existing

