language: python
python:
  - 3.8
before_install:
  - pip install -U pip
# command to install dependencies
install:
  - pip install -r requirements-dev.txt
  - pip install coveralls  # python-coveralls leads to this issue: https://github.com/z4r/python-coveralls/issues/73
  - pip install .
# command to run tests
script:
  - pytest --cov pyastar2d --cov-report term-missing
after_success:
  - coveralls
notifications:
  email: false
