---
# network
host: '0.0.0.0'
port: 5566

# map
map_file: './data/maps/test_5cm.png'
map_scale: 0.05

# display
robot_radius: 2 #For scale 0.05. 10 for scale 0.01

# simulation
start_pose:
  x: 0.5
  y: 1.0
  z: 0.0
use_noisy_pose: true
robot_phy_length: 0.32
position_noise_stddev: 0.05

# localization proxy
proxy_real_robot: off
proxy_host: 'localhost'
proxy_port: 5567

# logging
log_level: 'debug'

# clues
clues:
  - clue_id: 1
    trigger:
      x: 1.0
      y: 1.0
      r: 0.7
    location:
      x: 4.0
      y: 4.0
    audio_file: './data/audio/SM4_F48_A0100.wav'
  - clue_id: 2
    trigger:
      x: 3.0
      y: 1.5
      r: 0.8
    location:
      x: 1.0
      y: 2.5
    audio_file: './data/audio/SM4_F48_A0100.wav'


# targets
targets:
  - target_id: 1
    trigger:
      x: 2.0
      y: 2.0
      r: 0.2
    image_file: './data/imgs/fallen_person.jpeg'